Repository wielebenwir/commonsbooking, pull requests merged in 2023-06, with the labels that each got.

#1245 Update readme.txt tags to be more descriptive
  Readme.md
  readme.txt
Labels: quick, ready

#1262 fix bug sending cancellation mail to admin on admin cancellation #1261
  src/Model/Booking.php
  src/Wordpress/CustomPostType/Booking.php
  templates/booking-single.php
Labels: bug, ready, php

#1275 Bessere Buchungsvalidierung
  assets/public/sass/partials/_forms.scss
  commonsbooking.php
  src/Exception/BookingDeniedException.php
  src/Exception/OverlappingException.php
  src/Model/Booking.php
  src/View/Booking.php
  src/Wordpress/CustomPostType/Booking.php
  templates/booking-single-form.php
  templates/booking-single.php
  templates/item-single.php
  tests/Wordpress/CustomPostType/BookingTest.php
  tests/Wordpress/CustomPostTypeTest.php
Labels: bug

#1244 added other shortcodes to warmup #1243
  src/Service/Cache.php
Labels: bug, quick

#1167 added path option for cache #1166
  includes/OptionsArray.php
  src/Service/Cache.php
Labels: enhancement, ready, technical
