Repository wielebenwir/commonsbooking, pull requests merged in 2023-04, with the labels that each got.

#1149 fixes location without address not displayed correctly
  src/Model/Location.php
  src/Service/iCalendar.php
  templates/booking-single.php
  templates/location-calendar-header.php
Labels: bug, ready

#1152 additional unit tests
  src/Service/iCalendar.php
  tests/CB/CBTest.php
  tests/Model/BookingTest.php
  tests/Model/ItemTest.php
  tests/Model/LocationTest.php
  tests/Model/TimeframeTest.php
  tests/Repository/ItemTest.php
  tests/Service/iCalendarTest.php
  tests/Wordpress/CustomPostTypeTest.php
  tests/bootstrap.php
Labels: ready, technical

#1115 #1114 Optimize full-day handling & refactoring
  src/Model/Timeframe.php
  src/Repository/Booking.php
  src/Wordpress/CustomPostType/Booking.php
Labels: enhancement

#1222 Add whitelist filter for code and config files
  .github/workflows/php.yml
Labels: ready

#1231 Bessere Labels für Timeframes
  languages/commonsbooking-de_DE.mo
  languages/commonsbooking-de_DE.po
  languages/commonsbooking.pot
  src/Wordpress/CustomPostType/Timeframe.php
Labels: documentation

#1205 added deprecated filter hooks to schedule for removing
  src/Service/Scheduler.php
Labels: bug, quick, ready
