Repository wielebenwir/commonsbooking, pull requests merged in 2023-05, with the labels that each got.

#1177 TimeFrame Helper: Merge display of overlapping timeframes
  src/Helper/Helper.php
  templates/timeframe-withitem.php
  templates/timeframe-withlocation.php
  tests/Helper/HelperTest.php
Labels: enhancement, ready

#1271 fixes github action deprecation
  .github/workflows/php.yml
Labels: bug, quick, ready, technical

#1274 Behebt kaputte Übersetzungen iCalendar Titel
  languages/commonsbooking-de_DE.mo
  languages/commonsbooking-de_DE.po
  languages/commonsbooking.pot
  src/Plugin.php
Labels: bug, ready, i18n

#1141 Refactoring
  bin/install-wp-tests.sh
  includes/Users.php
  src/Exception/TimeframeInvalidException.php
  src/Helper/Wordpress.php
  src/Map/MapAdmin.php
  src/Model/Booking.php
  src/Model/Day.php
  src/Model/Restriction.php
  src/Model/Timeframe.php
  src/Plugin.php
  src/Repository/BookablePost.php
  src/Repository/BookingCodes.php
  src/Wordpress/CustomPostType/Map.php
  src/Wordpress/CustomPostType/Timeframe.php
  tests/Model/TimeframeTest.php
Labels: ready
