Repository wielebenwir/commonsbooking, pull requests merged in 2023-03, with the labels that each got.

#1188 Updated version support
  readme.txt
Labels: quick, ready

#1195 fixes #1194 Timeframe validation bug
  src/Model/Timeframe.php
  tests/Model/TimeframeTest.php
Labels: bug, ready

#1028 Feature/issue 871 / Allow admin bookings
  .gitignore
  assets/admin/css/admin.css
  assets/admin/css/admin.css.map
  assets/admin/js/admin.min.js
  assets/admin/sass/admin.scss
  assets/admin/sass/partials/_admin-edit.scss
  assets/global/js/vendor.js
  assets/global/js/vendor.js.map
  assets/global/js/vendor.min.js
  assets/public/css/public.css
  assets/public/css/public.css.map
  assets/public/js/public.min.js
  includes/Admin.php
  includes/Plugin.php
  languages/commonsbooking-de_DE.mo
  languages/commonsbooking-de_DE.po
  languages/commonsbooking.pot
  src/Helper/Wordpress.php
  src/Messages/AdminMessage.php
  src/Model/Booking.php
  src/Plugin.php
  src/Repository/Booking.php
  src/Wordpress/CustomPostType/Booking.php
  templates/booking-single-form.php
  templates/booking-single.php
Labels: enhancement
