Repository wielebenwir/commonsbooking, pull requests merged in 2025-06, with the labels that each got.

#1754 Litepicker: added filter hook for amount of months displayed (mobile)
  assets/public/js/public.js
  assets/public/js/src/lib/litepicker.js
  assets/public/js/src/litepicker.js
  docs/dokumentation/einstellungen/hooks-und-filter.md
  src/View/Calendar.php
Labels: enhancement

#1835 Uses translated strings in LitePicker instantiation, instead of static german labels
  assets/public/js/src/litepicker.js
  src/View/Item.php
  templates/timeframe-calendar.php
Labels: i18n

#1805 Feature/issue 1800 (Select Caching strategies)
  docs/.vitepress/config.mts
  docs/dokumentation/erweiterte-funktionalitaet/cache.md
  docs/dokumentation/haeufige-fragen-faq/die-seite-ist-sehr-langsam.md
  docs/en/documentation/advanced-functionality/cache.md
  includes/OptionsArray.php
  src/Service/Cache.php
  src/Service/Upgrade.php
  tests/php/Service/CacheTest.php
  tests/php/Service/UpgradeTest.php
Labels: enhancement

#1757 add cache warmup cronjob (#1679)
  docs/dokumentation/erweiterte-funktionalitaet/cache.md
  docs/en/documentation/advanced-functionality/cache.md
  includes/OptionsArray.php
  src/Service/Scheduler.php
Labels: enhancement, performance
